openai:
  api_key: 
    - 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
    - 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

# 
instructions:
  Spark: >- #spark using scala
    Given the following raw log, generate the corresponding log statement by identifying the variable parts and replacing them with appropriate placeholders, only return the log statements (code) without additional explainations:
  Windows: >- #windows using cpp
    Log message reverse: given a log message, the AI assistant can generate the corresponding code that generated the log message. The code must be like the following example: `log_printf("SQM: Failed to start upload with file pattern: %s, flags: %d [HRESULT = %d - E_FAIL]")`. And any possible varible in the log message must be replaced in the form of placeholder like the example. If a log message is given, only return the code without additional explainations.
  Windows_new: >-
    Log message reverse: given a log message, the AI assistant can generate the corresponding code that generated the log message. Any possible varible in the log message must be replaced in the form of placeholder If a log message is given, only return the code without additional explainations.